export const FETCH_DIAMONDS = 'FETCH_DIAMONDS';
export const FETCH_DIAMONDS_SUCCESS = 'FETCH_DIAMONDS_SUCCESS';
export const FETCH_DIAMONDS_FAILED = 'FETCH_DIAMONDS_FAILED';

export const ADD_DIAMOND = 'ADD_DIAMOND';
export const REMOVE_DIAMOND = 'REMOVE_DIAMOND';

export const SAVE_CART = 'SAVE_CART';
export const SAVE_CART_SUCCESS = 'SAVE_CART_SUCCESS';
export const SAVE_CART_FAILED = 'SAVE_CART_FAILED';
