#FROM node:6
#
#ENV RUNNER_UID 0
#ENV RUNNER_GID 0
#
#RUN mkdir -p /code
#ADD . /code
#
#WORKDIR /code
#
#RUN npm install
#RUN npm run build
#RUN chown -R ${RUNNER_UID}:${RUNNER_GID} /code/build
#
#VOLUME /code/build
#
#CMD tail -f /dev/null
