# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 08:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='shape',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage('/code/media'), upload_to='shapes/'),
        ),
    ]
